version: "3"
services:
  db:
    image: mariadb:10.4.8
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root-secure-password"
      MYSQL_USER: "pockett"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "pockett"